# Top level Makefile for One ROM
#
# Running this Makefile will generate the One ROM firmware binary in $BUILD_DIR
# according to the settings below.

VERSION_MAJOR := 0
VERSION_MINOR := 7
VERSION_PATCH := 3
BUILD_NUMBER := 1
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
export VERSION_MAJOR VERSION_MINOR VERSION_PATCH BUILD_NUMBER GIT_COMMIT

FIRMWARE_DIR := firmware
BUILD_DIR := $(FIRMWARE_DIR)/build

# probe-rs Chip ID
PROBE_RS_CHIP_ID=RP235X

# Device flash base
FLASH_BASE=0x10000000

#
# Settings
#
# Use these to specify your hardware variant and the ROM images and
# configuration.
#
#
# Development and debug settings
#
# It is recommended to leave these settings as is unless you are developing or
# debugging the One ROM firmware.
#
# However, if you are having problems with the One ROM firmware, you may want to
# disable any enabled features.
#

# Boot logging is not a build option.  It is compiled in unconditionally and
# switched at runtime from metadata, so it is set when a device is programmed -
# `onerom program --boot-logging true`.  A BOOT_LOGGING variable lived here
# until v0.7.2 and was read by nothing, so setting it silently did nothing.

# Plugin logging configuration
#
# Enables logs from plugins that support it.

PLUGIN_LOGGING ?= 0
# PLUGIN_LOGGING ?= 1

# Debug logging
#
# More extensive logging than the boot logging option.
#
# May overwhelm the SWD interface, meaning logs are dropped.
#
# This is not recommended for normal operation, but may be useful for debugging

DEBUG_LOGGING ?= 0
#DEBUG_LOGGING ?= 1

# Frequency
#
# Target frequency of the processor
# Leave blank to use the max frequency of the chip:
# - RP2350: 150MHz
#
# Your mileage may vary.  Faster machines will require the device to operate
# at higher frequencies.  Lower clock frequencies will cause One ROM to draw less
# power.
#
# It is suggested to leave this blank (i.e. use the maximum frequency) for most
# applications, and only dial it down if you are trying to reduce power
# consumption.

# FREQ ?= 30

# Output directory
#
# Directory to store intermediate files which are autogenerated during the
# build process.
GEN_OUTPUT_DIR ?= firmware/generated

# Cargo profile
#
# Whether to run cargo as release or debug.
# Needs to be blank for debug, because cargo.
CARGO_PROFILE ?= release

# Extra C Flags
#
# Use to pass extra flags into One ROM's compile stage.
#
# For example this enables the C main loop test function/
# EXTRA_C_FLAGS ?= -DC_MAIN_LOOP

EXTRA_C_FLAGS ?=


# Board - e.g. fire-32-a
#
# Only required when building the firmware using C-based metadata

BOARD ?= 


# Config - e.g. onerom-config/c64.json
#
# Only required when building the firmware using C-based metadata

CONFIG ?=

#
# End of settings
#

COLOUR_YELLOW := $(shell echo -e '\033[33m')
COLOUR_RESET := $(shell echo -e '\033[0m')
COLOUR_RED := $(shell echo -e '\033[31m')

ifneq ($(SUPPRESS_OUTPUT),1)
  $(info ==========================================)
  $(info Building One ROM v$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH))
  $(info ==========================================)
  $(info One ROM Makefile env settings:)
endif

# Sort out binary prefix
BIN_PREFIX=onerom-rp235x

# Extra C flags
ifneq ($(EXTRA_C_FLAGS),)
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - EXTRA_C_FLAGS=$(EXTRA_C_FLAGS))
endif
endif

# Set FREQ_FLAG based on FREQ variable
ifeq ($(FREQ),)
  FREQ_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - FREQ=$(FREQ))
endif
  FREQ_FLAG = --freq $(FREQ)
endif

ifeq ($(CONFIG),)
  CONFIG_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - CONFIG=$(CONFIG))
endif
  CONFIG_FLAG = --config $(CONFIG)
endif

ifeq ($(BOARD),)
  BOARD_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - BOARD=$(BOARD))
endif
  BOARD_FLAG = --board $(BOARD)
endif

# Set up CARGO_TARGET_DIR
ifeq ($(CARGO_PROFILE),)
  CARGO_TARGET_DIR := rust/target/debug
else
  CARGO_TARGET_DIR := rust/target/$(CARGO_PROFILE)
endif
ifneq ($(SUPPRESS_OUTPUT),1)
$(info - CARGO_TARGET_DIR=$(CARGO_TARGET_DIR))
endif

ifneq ($(ARGS),)
ifneq ($(SUPPRESS_OUTPUT),1)
$(info - ARGS=$(ARGS))
endif
endif

ifneq ($(SUPPRESS_OUTPUT),1)
$(info -----)
endif

# Strip the environment cargo injects into a build script, so that a cargo we
# launch sees the same ambient environment however we were reached.
#
# onerom-fw-emulator's build.rs runs `make libonerom-test`, which depends on
# gen-config, so the cargo invocations below happen both directly from a shell
# and nested inside that build script.  The nested one inherits CARGO_PKG_NAME,
# CARGO_CFG_*, OUT_DIR and some forty others from its parent.  Cargo checks
# `rerun-if-env-changed` variables against its own process environment, and
# ring's build script declares a rerun dependency on thirteen of them, so the
# two invocations disagree about ring and rebuild it — plus rustls, webpki,
# tokio-rustls, hyper-rustls, reqwest and onerom-fw behind it — every time they
# alternate.  That was ~18s on every one of the ~474 emulator tests.
#
# Scrub the whole injected set rather than the variables ring happens to read
# today: a dependency that tracks a different one would silently bring the
# rebuild back, and a partial scrub is indistinguishable from none.  Cargo's own
# configuration (CARGO_HOME, CARGO_TARGET_DIR, CARGO_BUILD_*, ...) is not part
# of that set and is deliberately left alone.
SCRUB_CARGO_ENV = for v in $$(env | grep -oE '^(CARGO_CFG_[A-Z_0-9]+|CARGO_FEATURE_[A-Z_0-9]+|CARGO_PKG_[A-Z_0-9]+|DEP_[A-Za-z_0-9]+)=' | tr -d '='); do unset "$$v"; done; \
	unset CARGO CARGO_MANIFEST_DIR CARGO_MANIFEST_PATH CARGO_MANIFEST_LINKS \
	      CARGO_MAKEFLAGS CARGO_ENCODED_RUSTFLAGS CARGO_CRATE_NAME CARGO_BIN_NAME \
	      OUT_DIR TARGET HOST NUM_JOBS OPT_LEVEL DEBUG PROFILE RUSTC RUSTDOC;

.PHONY: all clean clean-firmware clean-firmware-build firmware run flash test test-emu test-api test-monitor test-rbcp test-usb test-c generated clean-generated fw-config-gen libonerom-test libonerom-test-wasm gen-config clean-gen-config clean-libonerom-test clean-libonerom-test-wasm libonerom-test-cov clean-libonerom-test-cov cov-run cov-campaign cov-report cov-check cov-raise clean-coverage

all: firmware
	@echo "=========================================="
	@echo "One ROM firmware build complete:"
	@echo "- firmware files are in $(BUILD_DIR)/"
	@echo "-----"
	@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).elf
	@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).bin
	-@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).uf2
	@echo "=========================================="

generated: 
	@echo "=========================================="
	@echo "Building onerom-metadata, to generate metadata header file"
	@echo "-----"
	@$(SCRUB_CARGO_ENV) cd rust && cargo build --$(CARGO_PROFILE) -p onerom-metadata

fw-config-gen:
	@$(SCRUB_CARGO_ENV) cd rust && cargo build --$(CARGO_PROFILE) -p fw-config-gen --quiet

firmware: generated
	@echo "=========================================="
	@echo "Building One ROM firmware - RP235X"
	@echo "-----"
	@GEN_OUTPUT_DIR=$(GEN_OUTPUT_DIR) EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" BIN_PREFIX="$(BIN_PREFIX)" DEBUG_LOGGING=$(DEBUG_LOGGING) PLUGIN_LOGGING=$(PLUGIN_LOGGING) make --no-print-directory -C $(FIRMWARE_DIR)
	@if command -v picotool >/dev/null 2>&1; then \
		picotool uf2 convert $(BUILD_DIR)/$(BIN_PREFIX).bin $(BUILD_DIR)/$(BIN_PREFIX).uf2; \
	else \
		echo "Warning: picotool not found, skipping UF2 conversion"; \
	fi

run: firmware info
	@echo "=========================================="
	@echo "Flash One ROM firmware to device and attach to logging:"
	@echo "-----"
	@probe-rs run --chip $(PROBE_RS_CHIP_ID) $(BUILD_DIR)/$(BIN_PREFIX).elf

flash: firmware info
	@echo "=========================================="
	@echo "Flash One ROM firmware to device:"
	@echo "-----"
	@probe-rs download --chip $(PROBE_RS_CHIP_ID) --binary-format bin --base-address $(FLASH_BASE) $(BUILD_DIR)/$(BIN_PREFIX).bin

test: firmware
	@echo "=========================================="
	@echo "Building tests to:"
	@echo "- verify generated firmware ROM images"
	@echo "-----"
	@GEN_OUTPUT_DIR=$(GEN_OUTPUT_DIR) EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" make --no-print-directory -C test
	@echo "=========================================="
	@echo "Running tests to:"
	@echo "- verify generated firmware ROM images"
	@echo "-----"
	test/build/image-test
	@echo "-----"
	@echo "Tests completed"

gen-config: fw-config-gen
	@echo "=========================================="
	@echo "Generating C-based metadata"
	@echo "-----"
	@$(CARGO_TARGET_DIR)/fw-config-gen \
		$(CONFIG_FLAG) \
		--version $(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH).$(BUILD_NUMBER) \
		$(BOARD_FLAG) \
		--output $(GEN_OUTPUT_DIR)/gen-config.c

test-emu: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-fw-tester --bin pio-tester --quiet

test-api: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-fw-tester --bin plugin-api-tester --quiet

test-monitor: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-fw-tester --bin address-monitor-tester --quiet

test-rbcp: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-rbcp-tester --bin rbcp-tester --quiet

# The host C tests.  A coverage run drives this like any other tester - see
# ci/coverage-testers.txt - and COVERAGE_FW=1 is what makes it instrument.
test-c:
	@echo "=========================================="
	@echo "Running One ROM host C tests"
	@echo "-----"
	@COVERAGE_C=$(if $(COVERAGE_FW),1,0) ci/c-tests.sh

test-usb: gen-config
	@echo "=========================================="
	@echo "Running One ROM USB plugin tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-usb-tester --bin usb-tester --quiet -- $(USB_TESTER_ARGS)

# Coverage.  BOARD and CONFIG select what the testers run against, and are
# required - there is no sensible default, and a wrong one would be measured
# without comment.  See ci/coverage-run.sh.
cov-run:
	@ci/coverage-run.sh $(BOARD) $(CONFIG)

# The whole campaign - hours, and what moves the floors.  For the edit loop
# use cov-run against one board and config.
cov-campaign:
	@ci/coverage-campaign.sh

cov-report:
	@ci/coverage-report.sh

cov-check:
	@ci/coverage-report.sh --check

cov-raise:
	@ci/coverage-report.sh --raise

clean-coverage: clean-libonerom-test-cov
	@echo "Cleaning coverage build output"
	@rm -rf build/coverage
	@rm -rf build/c-tests-cov
	@rm -rf plugins/*/*/build-host-cov

libonerom-test: gen-config
	@echo "=========================================="
	@echo "Building libonerom-test"
	@echo "-----"
	EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" make --no-print-directory -C $(FIRMWARE_DIR) -f test.mk
	@echo "-----"
	@echo "Done building libonerom-test"

# WebAssembly build of libonerom-test (for One ROM Lens).  Cross-compiles with
# Emscripten into a separate build-wasm/ so it never clashes with the native
# build-test/ objects.  Driven by onerom-fw-emulator's build.rs when its cargo
# target is wasm.
libonerom-test-wasm: gen-config
	@echo "=========================================="
	@echo "Building libonerom-test (WebAssembly)"
	@echo "-----"
	EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" make --no-print-directory -C $(FIRMWARE_DIR) -f test.mk WASM=1 BUILD_DIR=build-wasm
	@echo "-----"
	@echo "Done building libonerom-test (WebAssembly)"

# Coverage build of libonerom-test, for the firmware coverage figures.  Built
# with --coverage into a separate build-test-cov/ so it never clashes with the
# ordinary build-test/ objects: the two differ only in flags, and an object
# does not depend on the flags it was compiled with.  Driven by
# onerom-fw-emulator's build.rs when COVERAGE_FW=1.
libonerom-test-cov: gen-config
	@echo "=========================================="
	@echo "Building libonerom-test (coverage)"
	@echo "-----"
	EXTRA_C_FLAGS="--coverage $(EXTRA_C_FLAGS)" make --no-print-directory -C $(FIRMWARE_DIR) -f test.mk BUILD_DIR=build-test-cov
	@echo "-----"
	@echo "Done building libonerom-test (coverage)"

-include $(GEN_OUTPUT_DIR)/generated.mk

clean-firmware-build:
	+cd $(FIRMWARE_DIR) && make clean-build

clean-firmware: clean-generated
	+cd $(FIRMWARE_DIR) && make clean

clean-generated:
	cd rust && cargo clean -p onerom-metadata
	cd firmware/generated && rm -f onerom_metadata.h

clean-rust:
	cd rust && cargo clean

clean-gen-config:
	cd firmware/generated && rm -f gen-config.c

clean-libonerom-test: clean-gen-config
	+cd $(FIRMWARE_DIR) && make -f test.mk clean-test

clean-libonerom-test-wasm: clean-gen-config
	+cd $(FIRMWARE_DIR) && make -f test.mk clean-test BUILD_DIR=build-wasm

clean-libonerom-test-cov: clean-gen-config
	+cd $(FIRMWARE_DIR) && make -f test.mk clean-test BUILD_DIR=build-test-cov

clean: clean-firmware clean-rust clean-generated clean-gen-config clean-libonerom-test clean-libonerom-test-wasm clean-coverage
