[package]
name = "studiov2-slot-builder"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "studiov2_slot_builder"
path = "src/lib.rs"

[[bin]]
name = "studiov2-slot-builder"
path = "src/main.rs"

[dependencies]
iced = { workspace = true, features = ["canvas", "tokio", "advanced"] }
studiov2-shared = { workspace = true }
onerom-config = { path = "../../../rust/config" }
onerom-gen = { path = "../../../rust/gen" }
rfd = "0.15"
serde_json = "1"
thiserror = { workspace = true }
tokio = { version = "1", features = ["rt"] }
png = { workspace = true }
