[package]
name = "onerom-metadata"
version = "0.2.0"
edition = "2024"
authors = ["Piers Finlayson <piers@piers.rocks>"]
license = "MIT"
description = "One ROM metadata handling"
repository = "https://github.com/piersfinlayson/one-rom"
homepage = "https://onerom.org"
documentation = "https://docs.rs/onerom-config"
keywords = ["retro", "rom", "embedded"]
categories = ["embedded", "hardware-support"]
build = "build/main.rs"

[lib]
name = "onerom_metadata"
 
[dependencies]
onerom-config = { workspace = true }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher", "inline-more"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde-big-array = "0.5"

[build-dependencies]
onerom-config = { workspace = true }
serde = { version = "1", features = ["derive"] }
toml  = { version = "1.1" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
[lints]
workspace = true
